### PR TITLE
Bugfix/91-cssparserhelper-unescape-url

### PR DESCRIPTION
**Pull request by shagkur**
This is the PR for issue #91

### CODE REVIEW

**Comment by phax** [comment]
Haha - also just started an implementation :)

**Comment by shagkur** [comment]
@phax Tell me if i should Decline this PR?

**Comment by phax** [comment]
@shagkur I like my version better because it is a bit "more clear", but I need to crosscheck the consistency to see if it is identical :)

**Comment by phax** [comment]
Anyway our effort is highly appreciated!!!

**Comment by phax** [comment]
Yes indeed, your implementation covers more chars.
But e.g. the special character selection does not seem to match the CSS3 syntax:

The release syntax of CSS v3 only uses the hex digits: https://www.w3.org/TR/css-syntax-3/#consume-an-escaped-code-point

Also CSS 2.1 syntax only allows hex-chars but not `" !"#$%&\()*+...`: https://www.w3.org/TR/CSS2/syndata.html#tokenization

So I would prefer to stick with the "standards based solution". What do you think?

**Comment by shagkur** [comment]
Indeed all these speical chars handling, as in my implementation, can be omitted and just passed on. I think, from looking at it in more detail, the only special one which needs to be even dropped is the escaped '\n', i.e. "\\\n". I believe that's the only one you need to consider in your implementation. Other than that i'm quite fine with your solution and am happy to decline this PR in favour of your fix.

**Comment by shagkur** [comment]
Btw. will the new released version be available on mavenrepository then?

**Comment by shagkur** [comment]
Closed in favour of @phax standard based fix

**Comment by phax** [comment]
Okay, noted. Yes of course the new version will be available on Maven Central as 7.0.1 soon

**Comment by phax** [comment]
Sorry, no release. See #93 and #91 for the explanation

**Pull request closed without merging**
