### PR TITLE
Error deprecated ie6/7 properties syntax

### PR DESCRIPTION
**Pull request by shagkur**

### CODE REVIEW

**Comment by phax** [comment]
Thanks @shagkur  Will look at it.
The main reason I was a bit reluctant is the unambiguity when using "calc". `a*b` is no longer resolvable....

**Comment by phax** [comment]
But your proposal to use it for the property only.... If that works for you....
Shall we make a "browser compliant" variation? Shoud we eventually insert a "legacy mode"?

**Comment by shagkur** [comment]
Well the thing is, for example following style declaration block:
```
div {
max-width: 100px;
*zoom: 1;
position: relative;
}
```
will result in
```
div {
max-width: 100px;
}
```
Which is wrong. At least in browser compliant mode. Just to give you the context to my issue.
However, the proposed solution works for me, because i only use in the property, as you said. BUT: I'm nowhere sure this is the right way to do so, especially about the parser syntax i use here. That's why i'm quite happy that you took a look and maybe you have a better and cleaner solution in mind.
Currently, when the parser hits `*zoom` it is not detected as an IDENT and hence will finally throw the ParseException in`styleDeclarationBlock()` because the parsed token does not match the expected one (RBRACE then). And hence will drop everything until the RBRACE.
I don't think there's a need for something like "legacy mode", supporting these IE hacks again. But as i wrote in the issue report, dropping (in browser compliant mode) for these properties in question, should only happen on that specific property.

**Comment by shagkur** [comment]
@phax Any opinion on my last comment?

**Comment by phax** [comment]
Opinion: yes - yet time: unfortunately not yet

**Comment by shagkur** [comment]
@phax No worries. :) I'll stick, in my project, with these changes since they work for me. But i'd be happy to discuss/work out this more detailed when you get some time to do so :)

**Comment by phax** [comment]
Yes sure - I just need to buy me some time :)

**Comment by shagkur** [comment]
@phax How about once in the evening? (j/k) :smiling_face_with_tear:

**Pull request merged**
